---
title: "ECDF"
subtitle: "With flipbookr and xaringan"
author: "Gina Reynolds"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = T, fig.retina = 3)
library(flipbookr)
```

---

```{r}
library(tidyverse)
library(patchwork)
```


---
class: inverse, center, middle

# Small N vis walk through

---

`r chunk_reveal("ecdf", break_type = "user", display_type = "output")`

---
class: inverse, center, middle

# Small N with code/vis walk through

---

`r chunk_reveal("ecdf")`


```{r ecdf, include=FALSE}
set.seed(780)
rnorm(20) %>% 
  tibble(var = .) %>% 
  arrange(var) %>% 
  mutate(index = 1:n()) -> 
df
  
ggplot(data = df) +
  aes(x = var) + 
  geom_rug() + #BREAK
  aes(y = index) + #BREAK
  geom_point() + #BREAK
  geom_step() + #BREAK
  aes(y = index / 20) + #BREAK
  stat_ecdf(color = "red") -> #BREAK
ecdf

ggplot(data = df) +
  aes(x = var) +
  geom_rug() + #BREAK
  geom_histogram(aes(group = index),
                 color = "black") + #BREAK
  geom_histogram(color = "black") + #BREAK
  geom_histogram() -> #BREAK
hist

ecdf / hist
```

---
class: inverse, center, middle

# larger N

---

`r chunk_reveal("ecdf_large")`

```{r ecdf_large, include=FALSE}
set.seed(780)
rnorm(200) %>% 
  tibble(var = .) %>% #BREAK
  arrange(var) %>% #BREAK
  mutate(index = 1:n()) -> #BREAK
df

ggplot(data = df) +
  aes(x = var) + 
  geom_rug() + #BREAK
  aes(y = index) + #BREAK
  geom_point() + #BREAK
  geom_step() + #BREAK
  aes(y = index / 200) + #BREAK
  stat_ecdf(color = "red")  -> #BREAK
ecdf
  
ggplot(data = df) +
  aes(x = var) +
  geom_rug() + #BREAK
  geom_histogram(aes(group = index),
                 color = "black") + #BREAK
  geom_histogram(color = "black") + #BREAK
  geom_histogram() -> #BREAK
hist

ecdf / hist
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
