---
title: "The art of flipbooking"
subtitle: "With flipbookr and xaringan"
author: "Gina Reynolds, December 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)
library(flipbookr)
library(tidyverse)
```


---

```{r}
rnorm(5, mean = 5, sd = 3) %>% 
  c(rnorm(4, mean = 10, sd = 2)) %>% 
  tibble(x = .) %>% 
  mutate(id = row_number()) ->
df

df %>% 
  bind_rows(df) %>%
  bind_rows(df) %>%
  bind_rows(df) %>%
  bind_rows(df) %>%
  bind_rows(df) %>%
  ggplot() +
  aes(x = x) +
  geom_rug() +
  geom_density(alpha = .2, color = "green", fill = "green") +
  aes(fill = as_factor(id)) +
  geom_density(alpha = .2, position = "stack")

```





---



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}
```
